"""Reporter agent: formats final output."""
from .base import BaseAgent

class ReporterAgent(BaseAgent):
    name = "reporter"
    
    def __init__(self, format='markdown'):
        self.format = format
    
    def process(self, input_data, context=None):
        analysis = context.get('analyzer', {}).get('analysis', '') if context else ''
        category = context.get('classifier', {}).get('category', 'general') if context else 'general'
        
        if self.format == 'markdown':
            report = f"""# Analysis Report

**Category**: {category}

## Summary

{analysis}

---
*Generated by Multi-Agent Workflow*
"""
        else:
            report = f"Category: {category}\n\n{analysis}"
        
        return {"report": report, "format": self.format}
